package parse_test

var files = []string{
	"../tq/Miscellaneous Frontend/Cutscene Figures.i7x",
	"../tq/Miscellaneous Frontend/ASCII Map.i7x",
	"../tq/Miscellaneous Frontend/Output Text.i7x",
	"../tq/Miscellaneous Frontend/Variable Text.i7x",
	"../tq/Miscellaneous Frontend/Parser Errors.i7x",
	"../tq/Miscellaneous Frontend/Status Bar.i7x",
	"../tq/Miscellaneous Frontend/Player Name.i7x",
	"../tq/Miscellaneous Frontend/Player Title.i7x",
	"../tq/Miscellaneous Frontend/Disclaimer.i7x",
	"../tq/Miscellaneous Frontend/Announcements.i7x",
	"../tq/Miscellaneous Frontend/Prologue.i7x",
	//"../tq/Miscellaneous Backend/Timer Stuff.i7x",
	"../tq/Miscellaneous Backend/Game Settings.i7x",
	"../tq/Miscellaneous Backend/Fetish Settings.i7x",
	"../tq/Fetish Settings/Gender Options.i7x",
	"../tq/Fetish Settings/Diaper Lover Options.i7x",
	"../tq/Fetish Settings/Pregnancy Options.i7x",
	"../tq/Fetish Settings/Instant TG Options.i7x",
	"../tq/Fetish Settings/Info Options.i7x",
	"../tq/Fetish Settings/Fetish Options.i7x",
	"../tq/Fetish Settings/Handicap Options.i7x",
	"../tq/Fetish Settings/Benefit Options.i7x",
	"../tq/Fetish Settings/DQ Benefit Options.i7x",
	"../tq/Fetish Settings/Background Options.i7x",
	"../tq/Fetish Settings/Secret Options.i7x",
	"../tq/Fetish Settings/Body Limit Options.i7x",
	"../tq/Fetish Settings/Festive Options.i7x",
	"../tq/Miscellaneous Backend/Engine Initialisation.i7x",
	"../tq/Miscellaneous Backend/Game Universe Initialisation.i7x",
	"../tq/Miscellaneous Frontend/Fainting.i7x",
	"../tq/Rooms/Static Rooms.i7x",
	"../tq/Rooms/Spatial Vectors and Shape.i7x",
	"../tq/Rooms/Solid Rock.i7x",
	"../tq/Rooms/Terra Incognita.i7x",
	"../tq/Rooms/Region Building Dungeon.i7x",
	"../tq/Rooms/Region Building Woods.i7x",
	"../tq/Rooms/Region Building Hotel.i7x",
	"../tq/Rooms/Region Building Mansion.i7x",
	"../tq/Rooms/Region Building School.i7x",
	"../tq/Rooms/Region Building.i7x",
	"../tq/Rooms/Deploying.i7x",
	"../tq/Rooms/Room Adjectives.i7x",
	"../tq/Rooms/Room Descriptions.i7x",
	"../tq/Rooms/Puddles.i7x",
	"../tq/Rooms/Dungeon.i7x",
	"../tq/Rooms/Woods.i7x",
	"../tq/Rooms/Hotel.i7x",
	"../tq/Objects/Laundry Robots.i7x",
	"../tq/Rooms/Barriers.i7x",
	"../tq/Rooms/Mansion.i7x",
	"../tq/Rooms/School.i7x",
	"../tq/Rooms/Predicament World.i7x",
	"../tq/Player/Gender.i7x",
	"../tq/Player/Fatigue.i7x",
	"../tq/Player/Misc Variables.i7x",
	"../tq/Body Parts/Body Parts Definitions.i7x",
	"../tq/Body Parts/Desirability.i7x",
	"../tq/Body Parts/Breasts.i7x",
	"../tq/Player/Stomach.i7x",
	"../tq/Body Parts/Belly.i7x",
	"../tq/Body Parts/Hips.i7x",
	"../tq/Body Parts/Vagina.i7x",
	"../tq/Body Parts/Asshole.i7x",
	"../tq/Body Parts/Face.i7x",
	"../tq/Body Parts/Thighs.i7x",
	"../tq/Body Parts/Arms.i7x",
	"../tq/Body Parts/Hair.i7x",
	"../tq/Body Parts/Penis.i7x",
	"../tq/Body Parts/Scrotum.i7x",
	"../tq/Player/Calculating Stats.i7x",
	"../tq/Player/Sex Addiction.i7x",
	"../tq/Player/Semen Addiction.i7x",
	"../tq/Player/Diaper Addiction.i7x",
	"../tq/Player/Delicateness.i7x",
	"../tq/Player/Appearance.i7x",
	"../tq/Player/Cringe Appearance.i7x",
	"../tq/Player/Heel Skill.i7x",
	"../tq/Player/Humiliation.i7x",
	"../tq/Player/Bimbo.i7x",
	"../tq/Player/Orifice Soreness.i7x",
	"../tq/Player/Body Soreness.i7x",
	"../tq/Player/Bladder.i7x",
	"../tq/Player/Weight Gain.i7x",
	"../tq/Player/Arousal.i7x",
	"../tq/Player/Classes.i7x",
	"../tq/Player/Skills.i7x",
	"../tq/Player/Magic Power.i7x",
	"../tq/Player/Short Skirt Addiction.i7x",
	"../tq/Player/Exposure Addiction.i7x",
	"../tq/Player/Rectum.i7x",
	"../tq/Player/Virginity.i7x",
	"../tq/Player/Avoiding Accidental Wetting.i7x",
	"../tq/Player/Orgasms.i7x",
	"../tq/Miscellaneous Backend/Liquid Movements.i7x",
	"../tq/Miscellaneous Backend/Teleporting and Dragging.i7x",
	"../tq/Miscellaneous Frontend/Taking Inventory.i7x",
	"../tq/Player Description/Overall Description.i7x",
	"../tq/Player Description/Soreness.i7x",
	"../tq/Player Description/Bimbo.i7x",
	"../tq/Player Description/Appearance.i7x",
	"../tq/Player Description/Heel Skill.i7x",
	"../tq/Player Description/Humiliation.i7x",
	"../tq/Player Description/Sex Addiction.i7x",
	"../tq/Player Description/Delicateness.i7x",
	"../tq/Player Description/TG.i7x",
	"../tq/Player Description/Status.i7x",
	"../tq/Player Description/Addictions.i7x",
	"../tq/Every Turn/Compute Turn.i7x",
	"../tq/Every Turn/Periodic Effects.i7x",
	"../tq/Every Turn/Stomach.i7x",
	"../tq/Every Turn/Reflection.i7x",
	"../tq/Every Turn/Flight.i7x",
	"../tq/Every Turn/Lactation.i7x",
	"../tq/Every Turn/Doom.i7x",
	"../tq/Every Turn/Pregnancy.i7x",
	"../tq/Every Turn/Semen Movements.i7x",
	"../tq/Every Turn/Diaper Orgasms.i7x",
	"../tq/Objects/Things Framework.i7x",
	"../tq/Drinks/Drinks Framework.i7x",
	"../tq/Drinks/Bottles.i7x",
	"../tq/Drinks/Cans.i7x",
	"../tq/Drinks/Vessels.i7x",
	"../tq/Drinks/Drink Effects.i7x",
	"../tq/Drinks/Dispensers.i7x",
	"../tq/Objects/Destroying.i7x",
	"../tq/Objects/Containers.i7x",
	"../tq/Objects/Mimic.i7x",
	"../tq/Actions/MimicInvestigating.i7x",
	"../tq/Objects/Candy Machine.i7x",
	"../tq/Objects/Trophies.i7x",
	"../tq/Objects/Altars.i7x",
	"../tq/Objects/Sacred Pool.i7x",
	"../tq/Objects/Hot Tub.i7x",
	"../tq/Objects/Swimming Pool.i7x",
	"../tq/Objects/Wardrobes.i7x",
	"../tq/Objects/Crafting Table.i7x",
	"../tq/Objects/Podium.i7x",
	"../tq/Objects/Well.i7x",
	"../tq/Objects/Dungeon Statue.i7x",
	"../tq/Objects/Woods Statue.i7x",
	"../tq/Objects/Mansion Statue.i7x",
	"../tq/Objects/Pink Sphere.i7x",
	"../tq/Objects/Summoning Portals.i7x",
	"../tq/Objects/Knife.i7x",
	"../tq/Objects/Cross Trainer.i7x",
	"../tq/Objects/PC Monitor.i7x",
	"../tq/Objects/Stop Button.i7x",
	"../tq/Objects/Gloryhole.i7x",
	"../tq/Objects/White Wall.i7x",
	"../tq/Objects/Warp Portal.i7x",
	"../tq/Objects/Tentacle Breeder.i7x",
	"../tq/Objects/Sewing Bench.i7x",
	"../tq/Collectibles/Collectible Definition.i7x",
	"../tq/Collectibles/Basic Collectibles.i7x",
	"../tq/Collectibles/Sanity Token.i7x",
	"../tq/Collectibles/Defiance Token.i7x",
	"../tq/Collectibles/Fabric Token.i7x",
	"../tq/Collectibles/Magic Token.i7x",
	"../tq/Collectibles/Doom Stuff.i7x",
	"../tq/Collectibles/Condom Pack.i7x",
	"../tq/Collectibles/Magic Lamp.i7x",
	"../tq/Collectibles/Eggs.i7x",
	"../tq/Collectibles/Soiled Diaper.i7x",
	"../tq/Consumables/Lubricant.i7x",
	"../tq/Consumables/Pink Pill.i7x",
	"../tq/Consumables/Christmas Gift.i7x",
	"../tq/Consumables/Make Up Kit.i7x",
	"../tq/Consumables/Electric Fan.i7x",
	"../tq/Consumables/Squeezy Bottle.i7x",
	"../tq/Consumables/Skeleton Key.i7x",
	"../tq/Consumables/Bandage.i7x",
	"../tq/Consumables/Dark Scroll.i7x",
	"../tq/Consumables/Wipes.i7x",
	"../tq/Traps/Trap Framework.i7x",
	"../tq/Traps/Makeup Pad Trap.i7x",
	"../tq/Traps/Ass Hook Trap.i7x",
	"../tq/Traps/Rocking Horse Trap.i7x",
	"../tq/Traps/Slingshot Trap.i7x",
	"../tq/Traps/Pink Smoke Pad Trap.i7x",
	"../tq/Traps/Needle Trap.i7x",
	"../tq/Traps/Paddle Trap.i7x",
	"../tq/Traps/Summoning Trap.i7x",
	"../tq/Traps/Sprinkle Trap.i7x",
	"../tq/Traps/Hypno Traps.i7x",
	"../tq/Traps/Tripwire Trap.i7x",
	"../tq/Traps/Camera Trap.i7x",
	"../tq/Traps/Magic Dust Trap.i7x",
	"../tq/Traps/Vines.i7x",
	"../tq/Traps/Baby Bouncer.i7x",
	"../tq/Traps/Discombobulator Laser Trap.i7x",
	"../tq/Traps/Haunted Mirror Trap.i7x",
	"../tq/Traps/Iron Maiden Trap.i7x",
	"../tq/Traps/Glue Trap.i7x",
	"../tq/Traps/Hole In Wall Trap.i7x",
	"../tq/Objects/Throne.i7x",
	"../tq/Crafting/Crafting Framework.i7x",
	"../tq/Crafting/Alchemy Products.i7x",
	"../tq/Crafting/Recipes.i7x",
	"../tq/Actions/Crafting.i7x",
	"../tq/Furniture/Furniture Framework.i7x",
	"../tq/Furniture/Kneeling Stool.i7x",
	"../tq/Furniture/Hammock.i7x",
	"../tq/Furniture/Hotel Bed.i7x",
	"../tq/Furniture/Royal Bed.i7x",
	"../tq/Furniture/Hotel Chairs.i7x",
	"../tq/Furniture/Modification Machine.i7x",
	"../tq/Furniture/Lecture Chair.i7x",
	"../tq/Furniture/Guest Bed.i7x",
	"../tq/Furniture/Master Bed.i7x",
	"../tq/Furniture/Med Bay Bed.i7x",
	"../tq/Furniture/Detention Chair.i7x",
	"../tq/Furniture/Basic Beds.i7x",
	"../tq/Food/Food Framework.i7x",
	"../tq/Food/Fae Mushroom.i7x",
	"../tq/Food/Candy.i7x",
	"../tq/Food/Bag Lunch.i7x",
	"../tq/Food/Chef Foods.i7x",
	"../tq/Food/Truffle.i7x",
	"../tq/Food/Cookie.i7x",
	"../tq/Food/Stuffed Mushroom.i7x",
	"../tq/Food/Gelatin.i7x",
	"../tq/Objects/Hotel Feeding Bowls.i7x",
	"../tq/Objects/School Food Machine.i7x",
	"../tq/Objects/School Drink Machine.i7x",
	"../tq/Food/Snacks.i7x",
	"../tq/Clothing/Clothing Adjectives.i7x",
	"../tq/Clothing/Orifice Protection.i7x",
	"../tq/Clothing/Clothing Functions.i7x",
	"../tq/Clothing/Clothing Setup.i7x",
	"../tq/Clothing/Outrage.i7x",
	"../tq/Clothing/Cringe.i7x",
	"../tq/Clothing/Printed Names.i7x",
	"../tq/Clothing/Description.i7x",
	"../tq/Clothing/Layering.i7x",
	"../tq/Clothing/Visibility.i7x",
	"../tq/Clothing/Summoning.i7x",
	"../tq/Clothing/Wearability.i7x",
	"../tq/Clothing/Removability.i7x",
	"../tq/Clothing/Magic State.i7x",
	"../tq/Clothing/Transformation.i7x",
	"../tq/Clothing/Influence.i7x",
	"../tq/Clothing/Imprinting.i7x",
	"../tq/Clothing/Quests.i7x",
	"../tq/Clothing/Themes.i7x",
	"../tq/Headgear/Headgear Framework.i7x",
	"../tq/Headgear/Tiara.i7x",
	"../tq/Headgear/Maid Headdress.i7x",
	"../tq/Headgear/Scrunchies.i7x",
	"../tq/Headgear/Cow Ears.i7x",
	"../tq/Headgear/Runic Headband.i7x",
	"../tq/Headgear/Flower Hairclip.i7x",
	"../tq/Headgear/Laurel Wreath.i7x",
	"../tq/Headgear/Royal Circlet.i7x",
	"../tq/Headgear/Rubber Top Hat.i7x",
	"../tq/Headgear/Hoods.i7x",
	"../tq/Headgear/Cat Ears.i7x",
	"../tq/Headgear/Sissy Bow.i7x",
	"../tq/Headgear/Baby Bonnet.i7x",
	"../tq/Headgear/Santa Hat.i7x",
	"../tq/Headgear/Demon Horns.i7x",
	"../tq/Headgear/Severed Tentacle.i7x",
	"../tq/Headgear/Wasp Antennae.i7x",
	"../tq/Headgear/Cultist Veil.i7x",
	"../tq/Headgear/Vampiric Fangs.i7x",
	"../tq/Headgear/Fox Ears.i7x",
	"../tq/Headgear/Puppy Ears.i7x",
	"../tq/Headgear/Glittering Rose.i7x",
	"../tq/Headgear/Cumdumpster Hat.i7x",
	"../tq/Headgear/Heart Hairpin.i7x",
	"../tq/Headgear/Combat Visor.i7x",
	"../tq/Headgear/Golden Tiara.i7x",
	"../tq/Headgear/Spiked Tiara.i7x",
	"../tq/Headgear/Rugged Headband.i7x",
	"../tq/Headgear/Halloween Headgear.i7x",
	"../tq/Headgear/Avatar Headpiece.i7x",
	"../tq/Shoes/Shoes Framework.i7x",
	"../tq/Shoes/All Shoes.i7x",
	"../tq/Shoes/Heels Framework.i7x",
	"../tq/Shoes/Boots.i7x",
	"../tq/Shoes/Peep Toe Heels.i7x",
	"../tq/Shoes/Platform Heels.i7x",
	"../tq/Shoes/Dildo Heels.i7x",
	"../tq/Shoes/Court Heels.i7x",
	//"../tq/Shoes/Girly Bow Court Heels.i7x",
	"../tq/Shoes/Wedge Heels.i7x",
	"../tq/Shoes/Ballet Heels.i7x",
	//"../tq/Shoes/Queen of Hearts Heels.i7x",
	"../tq/Shoes/Cow Pattern Boots.i7x",
	"../tq/Shoes/Ballet Shoes.i7x",
	"../tq/Shoes/Lipstick Heels.i7x",
	"../tq/Shoes/Armadillo Heels.i7x",
	"../tq/Shoes/Baby Booties.i7x",
	"../tq/Shoes/Mary Janes.i7x",
	"../tq/Shoes/Sandals.i7x",
	"../tq/Shoes/Trainee Boots.i7x",
	"../tq/Bra/Bra Framework.i7x",
	"../tq/Bra/All Bras.i7x",
	"../tq/Bra/White String Bikini Top.i7x",
	"../tq/Bra/Red String Bikini Top.i7x",
	"../tq/Bra/Cow Print Bikini Top.i7x",
	"../tq/Bra/Purple Bikini Top.i7x",
	"../tq/Bra/Leopard Print Bikini Top.i7x",
	"../tq/Bra/Silver Bikini Top.i7x",
	"../tq/Bra/Cream Bikini Top.i7x",
	"../tq/Bra/Skimpy Pink Bikini Top.i7x",
	"../tq/Bra/Pink Bikini Top.i7x",
	"../tq/Bra/Purple String Bikini Top.i7x",
	"../tq/Bra/Nipple Ring Bikini Top.i7x",
	"../tq/Knickers/Knickers Framework.i7x",
	"../tq/Knickers/Plug Panties.i7x",
	"../tq/Knickers/Cutoffs.i7x",
	"../tq/Knickers/Bikini Bottoms.i7x",
	"../tq/Knickers/Crotch Rope.i7x",
	"../tq/Knickers/Pouch Panties.i7x",
	"../tq/Knickers/Crotchless Panties.i7x",
	"../tq/Knickers/Hotpants.i7x",
	"../tq/Knickers/Bloomers.i7x",
	"../tq/Knickers/Microshorts.i7x",
	"../tq/Knickers/Strapon.i7x",
	"../tq/Knickers/Demonic Underwear.i7x",
	"../tq/Knickers/Portal Pants.i7x",
	"../tq/Knickers/Undies.i7x",
	"../tq/Knickers/G-Strings.i7x",
	"../tq/Knickers/Thongs.i7x",
	"../tq/Knickers/Briefs.i7x",
	"../tq/Knickers/Panties.i7x",
	"../tq/Knickers/Diaper Framework.i7x",
	"../tq/Knickers/Diapers.i7x",
	"../tq/Knickers/Diaper Covers.i7x",
	"../tq/Trousers/Trousers Framework.i7x",
	"../tq/Trousers/All Trousers.i7x",
	"../tq/Skirts/All Skirts.i7x",
	"../tq/Dresses/Dresses Framework.i7x",
	"../tq/Dresses/Swimsuit Framework.i7x",
	//"../tq/Dresses/Swimming Top.i7x",
	"../tq/Dresses/Monokinis.i7x",
	"../tq/Dresses/Slutty Monokinis.i7x",
	"../tq/Dresses/Royal Dress.i7x",
	"../tq/Dresses/Fishnet Dress.i7x",
	"../tq/Dresses/Maid Outfit.i7x",
	"../tq/Dresses/Blouse.i7x",
	"../tq/Dresses/Fetish Dress.i7x",
	"../tq/Dresses/Tube Top.i7x",
	"../tq/Dresses/Nighties.i7x",
	"../tq/Dresses/Cheerleader Outfit.i7x",
	"../tq/Dresses/Priestess Outfit.i7x",
	"../tq/Dresses/Schoolgirl Outfit.i7x",
	"../tq/Dresses/Evening Dress.i7x",
	"../tq/Dresses/Maternity Dress.i7x",
	"../tq/Dresses/Basque.i7x",
	"../tq/Dresses/Milking Harness.i7x",
	"../tq/Dresses/Fertility Goddess Outfit.i7x",
	"../tq/Dresses/Plastic Themed Dresses.i7x",
	"../tq/Dresses/Warrior's Chestpiece.i7x",
	"../tq/Dresses/T-Shirts.i7x",
	"../tq/Dresses/Clubbing Dress.i7x",
	"../tq/Dresses/Rope Harness.i7x",
	"../tq/Dresses/Negligee.i7x",
	"../tq/Dresses/Chainmail Top.i7x",
	"../tq/Dresses/Bodysuit.i7x",
	"../tq/Dresses/Shirt.i7x",
	"../tq/Dresses/Fishnet Top.i7x",
	"../tq/Dresses/Crop Top.i7x",
	"../tq/Dresses/Onesie.i7x",
	"../tq/Dresses/Demonic Dresses.i7x",
	"../tq/Dresses/Striped Top.i7x",
	"../tq/Dresses/Cultist Robe.i7x",
	"../tq/Dresses/Vest Top.i7x",
	"../tq/Dresses/Stealth Dresses.i7x",
	"../tq/Dresses/Butterfly Wings.i7x",
	"../tq/Dresses/ABDL Dresses.i7x",
	"../tq/Dresses/Ribbon Dress.i7x",
	"../tq/Dresses/Slave Dress.i7x",
	"../tq/Dresses/Business Dresses.i7x",
	"../tq/Dresses/Dining Dresses.i7x",
	"../tq/Dresses/Rubber Dress.i7x",
	"../tq/Dresses/Gingham Dress.i7x",
	"../tq/Dresses/Magical Dress.i7x",
	"../tq/Dresses/Christmas Dress.i7x",
	"../tq/Dresses/Bunny Outfit.i7x",
	"../tq/Dresses/Open Front Dress.i7x",
	"../tq/Dresses/Latex Dungarees.i7x",
	"../tq/Dresses/Halloween Dresses.i7x",
	"../tq/Dresses/Bridal Outfits.i7x",
	"../tq/Corsets/Corsets Framework.i7x",
	"../tq/Corsets/All Corsets.i7x",
	"../tq/Belts Suspenders/All Belts.i7x",
	"../tq/Stockings/All Stockings.i7x",
	"../tq/Accessories/Accessories Framework.i7x",
	"../tq/Accessories/Rings.i7x",
	"../tq/Accessories/Necklaces.i7x",
	"../tq/Accessories/Bracelets.i7x",
	"../tq/Accessories/Slave Collar.i7x",
	"../tq/Accessories/Pullstring Collar.i7x",
	"../tq/Accessories/Steel Collar.i7x",
	"../tq/Accessories/Bib.i7x",
	"../tq/Accessories/Lipstick Collar.i7x",
	"../tq/Accessories/Cumslut Collar.i7x",
	"../tq/Accessories/Fuckdoll Collar.i7x",
	"../tq/Accessories/Research Airhancer.i7x",
	"../tq/Accessories/Armband.i7x",
	"../tq/Piercings Modules/All Piercings.i7x",
	"../tq/Equippables/Equippables Framework.i7x",
	"../tq/Equippables/Whip of Domination.i7x",
	"../tq/Equippables/Magic Wand.i7x",
	"../tq/Equippables/Kitty Claws.i7x",
	"../tq/Equippables/Mittens.i7x",
	"../tq/Equippables/Swords.i7x",
	"../tq/Equippables/Prayer Beads.i7x",
	"../tq/Equippables/Pink Spraybottle.i7x",
	"../tq/Actions/Mopping.i7x",
	"../tq/Actions/Spritzing.i7x",
	"../tq/Equippables/Wasp Cloud.i7x",
	"../tq/Equippables/Vampiric Claws.i7x",
	"../tq/Equippables/Carrot Daggers.i7x",
	"../tq/Equippables/Royal Scepter.i7x",
	"../tq/Equippables/Pocketbooks.i7x",
	"../tq/Equippables/Midnight Tanto.i7x",
	"../tq/Equippables/Puppy Mittens.i7x",
	"../tq/Equippables/Fairy Wand.i7x",
	"../tq/Equippables/Nintendolls Wand.i7x",
	"../tq/Equippables/Fake Nails.i7x",
	"../tq/Equippables/Totem of Purity.i7x",
	"../tq/Equippables/Pom Poms.i7x",
	"../tq/Equippables/Heart Wand.i7x",
	"../tq/Equippables/Wrench.i7x",
	"../tq/Equippables/Heavy Club.i7x",
	"../tq/Bondage/Bondage Framework.i7x",
	"../tq/Bondage/Wrist Bondage.i7x",
	"../tq/Bondage/Ankle Bondage.i7x",
	"../tq/Objects/Dungeon Chains.i7x",
	"../tq/Bondage/Gags.i7x",
	"../tq/Bondage/Pacifiers.i7x",
	"../tq/Bondage/Puppy Gag.i7x",
	"../tq/Bondage/Rubber Duck Gag.i7x",
	"../tq/Bondage/Ring Gag.i7x",
	"../tq/Bondage/Portal Gag.i7x",
	"../tq/Bondage/Chastity Cage.i7x",
	//"../tq/Bondage/Pet Collar.i7x",
	"../tq/Bondage/Ball and Chain.i7x",
	"../tq/Bondage/Wrist Collar Bar.i7x",
	"../tq/Sex Toys/Sex Toy Framework.i7x",
	"../tq/Actions/Plugging.i7x",
	"../tq/Sex Toys/Golden Phallus.i7x",
	"../tq/Sex Toys/Throbbing Tentacle.i7x",
	"../tq/Sex Toys/Vibrator.i7x",
	"../tq/Sex Toys/Jelly Dildo.i7x",
	"../tq/Sex Toys/Mamba.i7x",
	"../tq/Sex Toys/Johnson.i7x",
	"../tq/Sex Toys/Cat Tail Plug.i7x",
	"../tq/Sex Toys/Bunny Tail Plug.i7x",
	"../tq/Sex Toys/Puppy Tail Plug.i7x",
	"../tq/Sex Toys/Demon Tail Plug.i7x",
	"../tq/Sex Toys/Prostate Massager Plug.i7x",
	"../tq/Sex Toys/Anal Beads.i7x",
	"../tq/Sex Toys/Ben Wa Balls.i7x",
	"../tq/Sex Toys/Unicorn Horn.i7x",
	"../tq/Sex Toys/Writhing Vine.i7x",
	"../tq/Clothing/Condom of Kings.i7x",
	"../tq/Tattoos/Tattoos Framework.i7x",
	"../tq/Tattoos/All Tattoos.i7x",
	"../tq/Actions/Inking.i7x",
	"../tq/Bags of Holding/Bags of Holding Framework.i7x",
	"../tq/Bags of Holding/Sacks of Holding.i7x",
	"../tq/Bags of Holding/Handbags of Holding.i7x",
	"../tq/Miscellaneous Backend/Relations.i7x",
	"../tq/Player/Immobility.i7x",
	"../tq/Player/Manual Dexterity.i7x",
	"../tq/Miscellaneous Backend/Nearby Simulated Danger.i7x",
	"../tq/Actions/Wearing.i7x",
	"../tq/Actions/Taking Off.i7x",
	"../tq/Actions/Displacing Replacing.i7x",
	"../tq/Actions/TopDisplacing TopReplacing.i7x",
	"../tq/Actions/Zipping.i7x",
	"../tq/Actions/Drinking.i7x",
	"../tq/Actions/Decanting.i7x",
	"../tq/Actions/Extracting.i7x",
	"../tq/Actions/Squirting.i7x",
	"../tq/Actions/Minibar Restocking.i7x",
	"../tq/Actions/Searching.i7x",
	"../tq/Actions/Opening.i7x",
	"../tq/Miscellaneous Backend/Items Found in Containers.i7x",
	"../tq/Actions/Pulling.i7x",
	"../tq/Actions/Jumping.i7x",
	"../tq/Actions/Standing.i7x",
	"../tq/Actions/Kneeling.i7x",
	"../tq/Actions/Going.i7x",
	"../tq/Actions/Returning.i7x",
	"../tq/Actions/Waiting.i7x",
	"../tq/Actions/Long Waiting.i7x",
	"../tq/Actions/Resting.i7x",
	"../tq/Actions/Taking.i7x",
	"../tq/Actions/Dropping.i7x",
	"../tq/Actions/Resisting.i7x",
	"../tq/Actions/Submitting.i7x",
	"../tq/Actions/Begging for Mercy.i7x",
	"../tq/Actions/Masturbating.i7x",
	"../tq/Actions/Showering.i7x",
	"../tq/Actions/Paying.i7x",
	"../tq/Actions/Giving.i7x",
	"../tq/Actions/Urinating.i7x",
	"../tq/Actions/Urinating Into Bottles.i7x",
	"../tq/Actions/Cleaning.i7x",
	"../tq/Actions/Eating.i7x",
	"../tq/Actions/Presenting.i7x",
	"../tq/Actions/Rinsing.i7x",
	"../tq/Actions/Squatting.i7x",
	"../tq/Actions/Offering Trading.i7x",
	"../tq/Actions/Invoking.i7x",
	"../tq/Actions/Poking.i7x",
	"../tq/Actions/Fainting.i7x",
	"../tq/Monster Framework/Monster Adjectives.i7x",
	"../tq/Monster Framework/Monster Descriptions.i7x",
	"../tq/Monster Framework/Monster Functions.i7x",
	"../tq/Monster Framework/Blocking.i7x",
	"../tq/Monster Framework/Set Up Monsters.i7x",
	"../tq/Monster Framework/Compute Monsters.i7x",
	"../tq/Monster Framework/Motion.i7x",
	"../tq/Monster Framework/Perception.i7x",
	"../tq/Monster Framework/Conversation.i7x",
	"../tq/Monster Framework/Interacting Protecting.i7x",
	"../tq/Monster Framework/Combat.i7x",
	"../tq/Monster Framework/DQ Punishments.i7x",
	"../tq/Monster Framework/Special Events.i7x",
	"../tq/Monster Framework/Diaper Events.i7x",
	"../tq/Monster Framework/Requested Sex.i7x",
	"../tq/Monster Framework/Penetrative Sex.i7x",
	"../tq/Monster Framework/Attacking Monsters.i7x",
	"../tq/Actions/Attacking.i7x",
	"../tq/Actions/Slapping.i7x",
	"../tq/Actions/Kneeing.i7x",
	"../tq/Actions/Kicking.i7x",
	"../tq/Monster Framework/Dominating Monsters.i7x",
	"../tq/Monster/Royal Guard.i7x",
	"../tq/Monster/Mannequin.i7x",
	"../tq/Monster/Demoness.i7x",
	"../tq/Monster/Gladiator.i7x",
	"../tq/Monster/Shopkeeper.i7x",
	"../tq/Monster/Vine Boss.i7x",
	"../tq/Monster/Fairy.i7x",
	"../tq/Monster/Witch.i7x",
	"../tq/Monster/Patron.i7x",
	"../tq/Monster/Real Life Patron.i7x",
	"../tq/Monster/Matron.i7x",
	"../tq/Monster Framework/Robots Framework.i7x",
	"../tq/Monster/RoboBellboy.i7x",
	"../tq/Monster/RoboButler.i7x",
	"../tq/Monster/RoboChef.i7x",
	"../tq/Monster/Wrestler.i7x",
	"../tq/Monster/Mechanic.i7x",
	"../tq/Monster/Demon Lord Xavier.i7x",
	"../tq/Monster/Dominatrix.i7x",
	"../tq/Monster/Mind Flayer.i7x",
	"../tq/Monster/Acolyte Cultist.i7x",
	"../tq/Monster/Ghost.i7x",
	"../tq/Monster/Deep One.i7x",
	"../tq/Monster/Vampiress.i7x",
	"../tq/Monster/Adult Baby Slave.i7x",
	"../tq/Monster/Herald Valleyhotep.i7x",
	"../tq/Monster/Djinn.i7x",
	"../tq/Monster/Kitsune.i7x",
	"../tq/Monster/Hellhound.i7x",
	"../tq/Monster/Pimp.i7x",
	"../tq/Monster/Princess.i7x",
	"../tq/Monster/Imp.i7x",
	"../tq/Monster Framework/Staff Framework.i7x",
	"../tq/Monster/Receptionist.i7x",
	"../tq/Monster/Headmistress.i7x",
	"../tq/Monster/Nurse.i7x",
	"../tq/Monster/Teachers Sapphire.i7x",
	"../tq/Monster/Teachers Emerald.i7x",
	"../tq/Monster/Teachers Ruby.i7x",
	"../tq/Monster/Teachers Pink Diamond.i7x",
	"../tq/Monster Framework/Student Framework.i7x",
	"../tq/Monster/Students Amicable.i7x",
	"../tq/Monster/Students Tryhard.i7x",
	"../tq/Monster/Students Innocent.i7x",
	"../tq/Monster/Students Nasty.i7x",
	"../tq/Monster/Students Ditzy.i7x",
	"../tq/Monster Framework/Supporter Framework.i7x",
	"../tq/Monster/Supporters.i7x",
	"../tq/Monster Framework/Woman Framework.i7x",
	"../tq/Actions/Talking.i7x",
	"../tq/Actions/Forbidden Actions.i7x",
	"../tq/Actions/Actions with Missing Nouns.i7x",
	"../tq/Miscellaneous Frontend/Tutorial.i7x",
	//"../tq/Ending the Game/Endgame Variables.i7x",
	//"../tq/Ending the Game/Endgame Images.i7x",
	//"../tq/Ending the Game/Epilogue Outcomes.i7x",
	//"../tq/Ending the Game/Reusable Content.i7x",
	//"../tq/Ending the Game/Ending the Game.i7x",
	//"../tq/Ending the Game/Transformation Reversal Options.i7x",
	//"../tq/Ending the Game/Body Score.i7x",
	//"../tq/Ending the Game/TQ DQ Nintendolls Job Epilogues.i7x",
	//"../tq/Ending the Game/TQ DQ One Year Later Epilogues.i7x",
	//"../tq/Character Window/[Danaume] [Keriax] [Wonderfuller] [Porn] [Strateg] TQ [DQ] Character Window.i7x",
	//"../tq/Miscellaneous Frontend/Debug Commands.i7x",
	//"../tq/Miscellaneous Backend/Donators Unlocks.i7x",
}
